### ISSUE TITLE
Uptime Goal - 24 Hours

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/discord.sh#1]
Migrating a ton of functions outside of the core of the bot should help us achieve this. 
Instead of a slash command executing a webull trade, we should implement a generic restful api and then migrate to gRPC. We could just do _straight to gRPC_ but sometimes we need to finish pre-school before we go straight to high school.

**Comment by jzanecook** [comment]
Closing since it doesn't seem to fit the scope of the recent pivot.

**Comment by jzanecook** [comment]
I was wrong

**Comment by jzanecook** [comment]
Closing as this concept is a continuous thing in everything we do all the time. Forever.
