### ISSUE TITLE
Concept: API

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/discord.sh#5]
**Core Concept**
A clear and concise description of what the concept is. Ex. It would be cool if [...]
API

* * *

- https://github.com/blitz-js/blitz
- Strapi v4

**Comment by h0lybyte** [comment]
- https://github.com/sahat/hackathon-starter
- https://github.com/w3tecch/express-typescript-boilerplate

**Comment by jzanecook** [comment]
[9:54 PM] Ziggy9263: https://github.com/w3tecch/express-typescript-boilerplate
[GitHub - w3tecch/express-typescript-boilerplate: A delightful way t...](https://github.com/w3tecch/express-typescript-boilerplate)
A delightful way to building a RESTful API with NodeJs &amp; TypeScript by @w3tecch - GitHub - w3tecch/express-typescript-boilerplate: A delightful way to building a RESTful API with NodeJs &am...
GitHub - w3tecch/express-typescript-boilerplate: A delightful way t...

[9:59 PM] Ziggy9263: https://github.com/async-labs/saas
[GitHub - async-labs/saas: Build your own SaaS business with SaaS bo...](https://github.com/async-labs/saas)
Build your own SaaS business with SaaS boilerplate. Productive stack: React, Material-UI, Next, MobX, WebSockets, Express, Node, Mongoose, MongoDB. Written with TypeScript. - GitHub - async-labs/sa...

[10:01 PM] H◈ly The Grayiron Jedi: https://web.archive.org/web/20201125103705/https://async-await.com/article/server-side-vs-client-side-rendering-in-react-apps
[Server-side vs client-side rendering in React apps](https://web.archive.org/web/20201125103705/https://async-await.com/article/server-side-vs-client-side-rendering-in-react-apps)
Server-side vs client-side rendering in React apps. React, Next.js, Material-UI, Express, Node. Practical considerations.

[10:06 PM] Ziggy9263: https://github.com/GeekyAnts/express-typescript
[GitHub - GeekyAnts/express-typescript: Express + TypeScript + Boile...](https://github.com/GeekyAnts/express-typescript)
Express + TypeScript + Boilerplate for Web / API App - GitHub - GeekyAnts/express-typescript: Express + TypeScript + Boilerplate for Web / API App
GitHub - GeekyAnts/express-typescript: Express + TypeScript + Boile...

[10:10 PM] Ziggy9263: https://github.com/sidhantpanda/docker-express-typescript-boilerplate
[GitHub - sidhantpanda/docker-express-typescript-boilerplate: A dock...](https://github.com/sidhantpanda/docker-express-typescript-boilerplate)
A dockerized TypeScript-Express App boilerplate with MongoDB and Github Actions - GitHub - sidhantpanda/docker-express-typescript-boilerplate: A dockerized TypeScript-Express App boilerplate with M...
GitHub - sidhantpanda/docker-express-typescript-boilerplate: A dock...

[10:12 PM] Ziggy9263: https://github.com/mkosir/express-typescript-typeorm-boilerplate

**Comment by jzanecook** [comment]
https://github.com/sidhantpanda/docker-express-typescript-boilerplate ******

**Comment by jzanecook** [comment]
Moving forward with Strapi.
